name:                opencl-examples
version:             0.1.0.0
github:              "lancelet/opencl-examples"
license:             BSD3
author:              "Jonathan Merritt"
maintainer:          "j.s.merritt@gmail.com"
copyright:           "2017 Jonathan Merritt"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Examples using the Haskell OpenCL package
description:         Please see the README on Github at <https://github.com/lancelet/opencl-examples#readme>

dependencies:
- base >= 4.7 && < 5
- CLUtil
- language-c-quote
- mainland-pretty
- OpenCL
- vector

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:

  01-hello-world:
    main:        Main.hs
    source-dirs: app/01-hello-world
    ghc-options: *exe-ghc-options
